PUT http://localhost:8080/events/1
Content-Type: application/json

{
    "name": "Test Event 2",
    "description": "Updated test event",
    "location": "A test location",
    "datetime": "2025-01-01T15:30:00.000Z"
}